framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - App\Messenger\AuditMiddleware
                    # - validation # but it's better to validate data before sending them to the bus...
                    # - doctrine_transaction # Wrap the handler inside a Doctrine transaction

            query.bus: ~

            event.bus:
                default_middleware: allow_no_handlers # An event have 0+ handler(s)
                middleware:
                    - App\Messenger\AuditMiddleware

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: null # messenger.transport.symfony_serializer
                options:
                    exchange: # for RabbitMQ
                        name: messages
                        type: direct #instead of fanout
                        default_publish_routing_key: normal
                    queues:
                        messages_normal:
                            binding_keys: [normal]
                retry_strategy:
                    service: null  # Implement RetryServiceInterface to customize ;)
                    max_retries: 5
                    delay: 1000
                    multiplier: 3
                    max_delay: 0

            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: high
                    exchange:  # for RabbitMQ
                        name: messages_high_priority
                        type: direct
                        default_publish_routing_key: high
                    queues:
                        messages_high:
                            binding_keys: [high]

            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Message\Command\AddDog': async_priority_high
            'App\Message\Command\RemoveDog': async_priority_high
            'App\Message\Command\DeleteDogFile': async
            'App\Message\Event\DeleteDogFileEvent': async

