version: '3.8'

services:
    database:
        image: mysql:${DATABASE_VERSION}
        command: --default-authentication-plugin=mysql_native_password
        container_name: ${APP_NAME}-db
        restart: unless-stopped
        ports:
            - 3306:3306
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - data-messenger:/var/lib/mysql
            - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf:ro
        networks:
            - backend

    php-fpm:
        build:
            context: ./docker-compose/php-fpm
            dockerfile: Dockerfile
        container_name: ${APP_NAME}-php-fpm
        restart: unless-stopped
        environment:
            COMPOSER_MEMORY_LIMIT: -1
        depends_on:
            - database
        volumes:
            - ./:/var/www
            - ./:/var/www/var:delegated # Fix mutagen permission error on var
            - ./docker-compose/php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
            - ./docker-compose/php-fpm/zz-blackfire.ini:/usr/local/etc/php/conf.d/zz-blackfire.ini:ro
            - ./docker-compose/php-fpm/supervisor/conf.d:/etc/supervisor/conf.d:ro
            - ./docker-compose/php-fpm/supervisor/supervisor.conf:/etc/supervisor/supervisor.conf:ro
        networks:
            - backend

    web_server:
        image: nginx:1.19-alpine
        container_name: ${APP_NAME}-web
        restart: unless-stopped
        expose:
            - 80
        ports:
            - 80:80
        volumes:
            - ./:/var/www:delegated
            - ./docker-compose/logs/nginx:/var/log/nginx
            # todo use COPY in Dockerfile instead
            - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d:ro
            - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker-compose/nginx/sites-available/:/etc/nginx/sites-available:ro
        depends_on:
            - php-fpm
        networks:
            - backend
        working_dir: /var/www
        command: [nginx-debug, '-g', 'daemon off;']

volumes:
    data-messenger:
        driver: local
networks:
    backend:
        driver: bridge
